#!/usr/bin/python3
import sys, os
from os.path import isfile
from verifier.xml_checker import check_
from parser_rail.parser import parseRailML
from lxml import etree
from colorama import Fore, Back, Style


# Main function which is gonna call the Schema validator, the parser and then the validator.
def main():

  if len(sys.argv) == 2 and isfile('./examples/'+sys.argv[1]):

    f = './examples/' + sys.argv[1]
    f = os.path.abspath(f)

    base, ext = os.path.splitext(f)
    if ext.lower() not in ('.xml'):
      print("ERROR: File given isn't a xml file.")
      sys.exit()

    # Validate Schema
    r = parseRailML(f)
    # Validate xml
    check_(f)

  else:
    print('Must give a file as input.')
    sys.exit()

main()
