#!/usr/bin/python3
from jjcli import *
import tkinter as tk
from tkinter import filedialog

def main ():
  s = """
  ╔═════════════════════════════════════════════════════════════════════════╗
  ║                                                                         ║
  ║                            Validator RailML                             ║
  ║                                                                         ║
  ║                               by Group 72                               ║
  ║                                                                         ║
  ╠═════════════════════════════════════════════════════════════════════════╣
  ║                                                                         ║
  ║  This is the main menu.                                                 ║
  ║                                                                         ║
  ╠═════════════════════════════════════════════════════════════════════════╣
  ║                                                                         ║
  ║    1 - Upload RailML File.                                              ║
  ║    2 - Validate RailML File.                                            ║
  ║    3 - Visualize RailML File.                                           ║
  ║    4 - Exit.                                                            ║
  ║                                                                         ║
  ║                                                                         ║
  ║  EQUIPE: José Pedro Silva + Luís Ribeiro + Pedro Rodrigues              ║
  ║                                                                         ║
  ║                                                                         ║
  ╚═════════════════════════════════════════════════════════════════════════╝
  """
  print(s)

  while True:
    try:
      option = input("? ").strip()
      try:
        val = int(option)
        if not (1 <= val <= 4):
          print("ERROR: Please enter a valid option number.")
        else:
          print("OK")
          if (val == 1):
            root = tk.Tk()
            root.withdraw()

            filename = filedialog.askopenfilename()
            print(filename)
            # call upload function
            # read to xml struct
          elif (val == 2):
            # Validate file.
          elif (val == 3):
            # visualize graph. Only after uploaded file.
          elif (val == 4):
            sys.exit()

      except ValueError:
        print("ERROR: That's not a number.")


    except KeyboardInterrupt:
      sys.exit()


main()
