#!/usr/bin/python3
from jjcli import *
import tkinter as tk
from tkinter import filedialog
from colorama import Fore, Back, Style

def main ():
  s = f"""
  ╔═════════════════════════════════════════════════════════════════════════╗
  ║                                                                         ║
  ║                            Validator RailML                             ║
  ║                                                                         ║
  ║                               by Group 72                               ║
  ║                                                                         ║
  ╠═════════════════════════════════════════════════════════════════════════╣
  ║                                                                         ║
  ║  This is the main menu.                                                 ║
  ║                                                                         ║
  ╠═════════════════════════════════════════════════════════════════════════╣
  ║                                                                         ║
  ║    1 - Upload RailML File.                                              ║
  ║    2 - Validate RailML File.                                            ║
  ║    3 - Visualize RailML File.                                           ║
  ║    4 - Exit.                                                            ║
  ║                                                                         ║
  ║                                                                         ║
  ║  EQUIPE: José Pedro Silva + Luís Ribeiro + Pedro Rodrigues              ║
  ║                                                                         ║
  ║                                                                         ║
  ╚═════════════════════════════════════════════════════════════════════════╝
  """
  print(s)
  uploaded = 0

  while True:
    try:
      option = input("? ").strip()
      try:
        val = int(option)
        if not (1 <= val <= 4):
          print("ERROR: Please enter a valid option number.")
        else:
          print("OK")
          if (val == 1):

            while uploaded == 1:
              opt = input(Fore.RED + 'Are you sure you want to update another file? [y/N]').strip()
              print(Style.RESET_ALL, end="")

              if opt == "y" or opt == "Y":
                uploaded = 0
              elif opt == "n" or opt == "N" or opt == "":
                break

            if uploaded == 0:
              root = tk.Tk()
              root.withdraw()
              filename = filedialog.askopenfilename(initialdir = ".",
                                          title = "Select a XML File",
                                          filetypes = [("XML files",
                                                        "*.xml")])
              uploaded = 1

            # read to xml struct
          elif (val == 2):
            # Validate file.
            sys.exit()
          elif (val == 3):
            # visualize graph. Only after uploaded file.
            sys.exit()
          elif (val == 4):
            sys.exit()

      except ValueError:
        print("ERROR: That's not a number.")


    except KeyboardInterrupt:
      sys.exit()


main()
